# Generated by Django 5.1 on 2025-07-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('nomrc', models.TextField(primary_key=True, serialize=False)),
                ('n_enregistrement', models.IntegerField()),
                ('datsaisi_c', models.DateField()),
            ],
            options={
                'db_table': 'collecte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indexation',
            fields=[
                ('nomi', models.TextField(primary_key=True, serialize=False)),
                ('n_enregistrement', models.IntegerField()),
                ('dat_reception', models.DateField()),
                ('dat_indexation', models.DateField()),
                ('dat_saisi', models.DateField()),
                ('dat_envoi', models.DateField()),
            ],
            options={
                'db_table': 'indexation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indexeur',
            fields=[
                ('nomi', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'indexeur',
                'managed': False,
            },
        ),
    ]
