# Generated by Django 5.1.7 on 2025-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collecteur',
            fields=[
                ('nomrc', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Collecteur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indexation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomi', models.TextField()),
                ('n_enregistrement', models.IntegerField()),
                ('dat_reception', models.DateField()),
                ('dat_indexation', models.DateField()),
                ('dat_saisi', models.DateField()),
                ('dat_envoi', models.DateField()),
            ],
            options={
                'db_table': 'indexation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indexeur',
            fields=[
                ('nomi', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'indexeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomrc', models.CharField(max_length=255)),
                ('n_enregistrement', models.IntegerField()),
                ('datsaisi_c', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collecte',
            },
        ),
    ]
