# Generated by Django 5.1.7 on 2025-07-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collecte',
            unique_together={('nomrc', 'n_enregistrement')},
        ),
    ]
