# Generated by Django 5.1 on 2025-07-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('nomc', models.TextField(primary_key=True, serialize=False)),
                ('dat_ctrl', models.DateField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('retourne', models.TextField()),
                ('dat_retour', models.DateField(blank=True, null=True)),
                ('dat_valid', models.DateField()),
                ('visa', models.TextField()),
                ('n_enregistrement', models.IntegerField()),
                ('dat_recepc', models.DateField()),
            ],
            options={
                'db_table': 'control',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Controleur',
            fields=[
                ('nomc', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'controleur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Controleurpv',
            fields=[
                ('controleur', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'controleurpv',
                'managed': False,
            },
        ),
    ]
