# Generated by Django 5.1 on 2025-07-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suiveur',
            fields=[
                ('noms', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'suiveur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.TextField()),
                ('n_enregistrement', models.IntegerField()),
                ('datenvoi_t', models.DateField()),
                ('dat_rsuivi', models.DateField()),
                ('datsaisi_ic', models.DateField()),
                ('datenvoi_sir', models.DateField()),
                ('dat_pv', models.DateField()),
                ('dat_mont', models.DateField()),
                ('dat_rrsuivi', models.DateField()),
                ('datsaisi_pv', models.DateField()),
            ],
            options={
                'db_table': 'suivi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vue',
            fields=[
                ('controleur', models.TextField(primary_key=True, serialize=False)),
                ('n_enregistrement', models.IntegerField()),
                ('dat_ctrl', models.DateField()),
                ('visa', models.TextField()),
                ('dat_recepv', models.DateField()),
            ],
            options={
                'db_table': 'vue',
                'managed': False,
            },
        ),
    ]
