# Generated by Django 5.1 on 2025-07-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('email', models.TextField()),
                ('login', models.TextField()),
                ('pass_field', models.TextField(db_column='pass')),
                ('destination', models.TextField()),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.TextField()),
            ],
            options={
                'db_table': 'auteur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('type', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'depot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('n_enregistrement', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('titre_article', models.TextField(blank=True, null=True)),
                ('pages', models.TextField(blank=True, null=True)),
                ('domaine', models.TextField()),
                ('type', models.TextField()),
                ('periodicite', models.TextField(blank=True, null=True)),
                ('vol', models.TextField()),
                ('tom', models.TextField()),
                ('num', models.TextField()),
                ('statut', models.TextField()),
                ('n_periodique', models.IntegerField(blank=True, null=True)),
                ('lang', models.TextField()),
            ],
            options={
                'db_table': 'doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('domaine', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'domaine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ecriture',
            fields=[
                ('auteur', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ecriture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('editeur', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'editeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('editeur', models.TextField(primary_key=True, serialize=False)),
                ('n_enregistrement', models.IntegerField()),
                ('date_edition', models.DateField()),
                ('ville_edition', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fournit',
            fields=[
                ('source', models.TextField(primary_key=True, serialize=False)),
                ('n_enregistrement', models.IntegerField()),
                ('date_reception', models.DateField()),
                ('obligation', models.TextField()),
            ],
            options={
                'db_table': 'fournit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
    ]
